name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  scan:
    name: Build & Scan Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Backend Image
      - name: Build backend Docker image
        run: |
          docker build -t docker.io/notyusheng/pdf-backend:${{ github.sha }} ./backend

      # Scan Backend Image with Trivy
      - name: Run Trivy on backend image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/notyusheng/pdf-backend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-backend-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Upload Backend Scan Results
      - name: Upload backend scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: 'trivy-backend'

      # Build Frontend Image
      - name: Build frontend Docker image
        run: |
          docker build -t docker.io/notyusheng/pdf-frontend:${{ github.sha }} ./frontend

      # Scan Frontend Image with Trivy
      - name: Run Trivy on frontend image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/notyusheng/pdf-frontend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-frontend-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Upload Frontend Scan Results
      - name: Upload frontend scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-frontend-results.sarif'
          category: 'trivy-frontend'

      # Build Nginx Image
      - name: Build nginx Docker image
        run: |
          docker build -t docker.io/notyusheng/pdf-nginx:${{ github.sha }} ./nginx

      # Scan Nginx Image with Trivy
      - name: Run Trivy on nginx image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/notyusheng/pdf-nginx:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-nginx-results.sarif'
          severity: 'CRITICAL,HIGH'
          timeout: 10m

      # Upload Nginx Scan Results
      - name: Upload nginx scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-nginx-results.sarif'
          category: 'trivy-nginx'
